In [1]:
import requests
import pandas as pd
import datetime
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
date_from = '2022-01-01'
date_to = str(datetime.date.today())

req_url = f'https://leadgid.api.hasoffers.com/Apiv3/json?api_key=4dc79c63460150a918972cf84c9c4557ff0d063b1252d267fe50f9fcb5abf127&Target=Affiliate_Report&Method=getStats&fields[]=Stat.date&fields[]=Stat.affiliate_info3&fields[]=Stat.affiliate_info2&fields[]=Stat.affiliate_info1&fields[]=Stat.payout&fields[]=Stat.clicks&fields[]=Stat.offer_id&fields[]=Offer.name&filters[Stat.date][conditional]=BETWEEN&filters[Stat.date][values][]={date_from}&filters[Stat.date][values][]={date_to}&limit=5000'
req = requests.get(req_url).json()

In [3]:
conversion_list = []
columns = ['date', 'offer_name', 'offer_id', 'sub1', 'sub2', 'sub3', 'payout', 'clicks']

for item in req['response']['data']['data']:
    date = item['Stat']['date']
    offer_name = item['Offer']['name']
    offer_id = item['Stat']['offer_id']
    sub1 = item['Stat']['affiliate_info1']
    sub2 = item['Stat']['affiliate_info2']
    sub3 = item['Stat']['affiliate_info3']
    payout = item['Stat']['payout']
    clicks = item['Stat']['clicks']

    conversion_list.append([date, offer_name, offer_id, sub1, sub2, sub3, payout, clicks])

In [4]:
df = pd.DataFrame(columns=columns, data=conversion_list)
df['date'] = pd.to_datetime(df['date'])
df['payout'] = pd.to_numeric(df['payout'])
df['clicks'] = df['clicks'].astype('int')
df['EPC'] = (df['payout'] / df['clicks']).round(2)
df['week'] = df['date'].dt.isocalendar().week
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

df.head(15)

,date,offer_name,offer_id,sub1,sub2,sub3,payout,clicks,EPC,week,month,year
0,2022-01-01,VIVA деньги - онлайн выдача,5141,ppp,,,26600.0,450,59.11,52,1,2022
1,2022-01-01,Займер - выдача микрокредита,1621,sm,d0q2,,14220.0,199,71.46,52,1,2022
2,2022-01-01,ДоЗарплаты - выданный заём,2323,sm,d0q3,,2600.0,155,16.77,52,1,2022
3,2022-01-01,Webbankir - выданный заём,3127,sm,d1q2,bounce,170.0,17,10.00,52,1,2022
4,2022-01-01,Pay P.S. - Выданный заём,4412,sm,d1q2,bounce,1650.0,42,39.29,52,1,2022
5,2022-01-01,Быстроденьги - выданный займ онлайн,4464,sm,d1q2,bounce,2800.0,36,77.78,52,1,2022
6,2022-01-01,BelkaCredit - выдача,4472,sm,d1q2,bounce,1440.0,92,15.65,52,1,2022
7,2022-01-01,Е - капуста - Заявка заполненная клиентом с хо...,1658,sm,d0q1,kapusta_check,6300.0,76,82.89,52,1,2022
8,2022-01-01,Moneyman - Выдача новому клиенту (VIP),5024,sm,d0q1,moneyman_check,11250.0,82,137.20,52,1,2022
9,2022-01-01,Moneyman - Выдача новому клиенту (VIP),5024,sm,d1q1,moneyman_check,7500.0,55,136.36,52,1,2022
10,2022-01-01,Займер - выдача микрокредита,1621,sm,d0q1,random,7110.0,88,80.80,52,1,2022
11,2022-01-01,ТУРБОЗАЙМ - Выданный займ,2577,sm,d0q1,random,9120.0,133,68.57,52,1,2022
12,2022-01-01,Pay P.S. - Выданный заём,4412,sm,d0q1,random,9900.0,84,117.86,52,1,2022
13,2022-01-01,VIVA деньги - онлайн выдача,5141,sm,d0q1,random,11400.0,51,223.53,52,1,2022
14,2022-01-01,Займ-Экспресс - онлайн-выдача,3331,sm,d1q1,vitrina,0.0,26,0.00,52,1,2022

In [6]:
df['sub3'].unique()

array(['', 'bounce', 'kapusta_check', 'moneyman_check', 'random',
       'vitrina', 'vitrina_lk', 'vivus_check', 'webbankir_check',
       'adwords'], dtype=object)

In [7]:
check_list = ['kapusta_check', 'moneyman_check', 'vivus_check', 'webbankir_check']

In [8]:
checker = df.query('sub3 in @check_list')

In [9]:
checker

,date,offer_name,offer_id,sub1,sub2,sub3,payout,clicks,EPC,week,month,year
7,2022-01-01,Е - капуста - Заявка заполненная клиентом с хо...,1658,sm,d0q1,kapusta_check,6300.0,76,82.89,52,1,2022
8,2022-01-01,Moneyman - Выдача новому клиенту (VIP),5024,sm,d0q1,moneyman_check,11250.0,82,137.20,52,1,2022
9,2022-01-01,Moneyman - Выдача новому клиенту (VIP),5024,sm,d1q1,moneyman_check,7500.0,55,136.36,52,1,2022
22,2022-01-01,Vivus - Выдача,1782,sm,d0q1,vivus_check,1445.0,88,16.42,52,1,2022
23,2022-01-01,Webbankir - выданный заём,3127,sm,d0q1,webbankir_check,6800.0,65,104.62,52,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
296,2022-01-14,Е - капуста - Заявка заполненная клиентом с хо...,1658,sm,d0q1,kapusta_check,10500.0,69,152.17,2,1,2022
297,2022-01-14,Moneyman - Выдача новому клиенту (VIP),5024,sm,d0q1,moneyman_check,11250.0,97,115.98,2,1,2022
298,2022-01-14,Moneyman - Выдача новому клиенту (VIP),5024,sm,d1q1,moneyman_check,0.0,39,0.00,2,1,2022
306,2022-01-14,Vivus - Выдача,1782,sm,d0q1,vivus_check,5780.0,84,68.81,2,1,2022
307,2022-01-14,Webbankir - выданный заём,3127,sm,d0q1,webbankir_check,12240.0,69,177.39,2,1,2022